CREATE TABLE IF NOT EXISTS companies (
    company_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    fiscal_year_start   DATE NOT NULL,
    closing_day         INTEGER NOT NULL DEFAULT 31,
    tax_entry_method    VARCHAR(20) NOT NULL DEFAULT 'gross',
    is_tax_exempt       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS closing_day INTEGER;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS tax_entry_method VARCHAR(20);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS is_tax_exempt BOOLEAN;
UPDATE companies
SET closing_day = 31
WHERE closing_day IS NULL;
UPDATE companies
SET tax_entry_method = 'gross'
WHERE tax_entry_method IS NULL;
UPDATE companies
SET is_tax_exempt = FALSE
WHERE is_tax_exempt IS NULL;
UPDATE companies
SET tax_entry_method = 'gross'
WHERE is_tax_exempt = TRUE;
ALTER TABLE companies ALTER COLUMN closing_day SET DEFAULT 31;
ALTER TABLE companies ALTER COLUMN closing_day SET NOT NULL;
ALTER TABLE companies ALTER COLUMN tax_entry_method SET DEFAULT 'gross';
ALTER TABLE companies ALTER COLUMN tax_entry_method SET NOT NULL;
ALTER TABLE companies ALTER COLUMN is_tax_exempt SET DEFAULT FALSE;
ALTER TABLE companies ALTER COLUMN is_tax_exempt SET NOT NULL;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'companies'
          AND constraint_name = 'companies_closing_day_check'
    ) THEN
        ALTER TABLE companies
        ADD CONSTRAINT companies_closing_day_check
        CHECK (closing_day BETWEEN 1 AND 31);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'companies'
          AND constraint_name = 'companies_tax_entry_method_check'
    ) THEN
        ALTER TABLE companies
        ADD CONSTRAINT companies_tax_entry_method_check
        CHECK (tax_entry_method IN ('gross', 'net'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
    user_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id            VARCHAR(100) NOT NULL UNIQUE,
    display_name        VARCHAR(100) NOT NULL,
    password_hash       VARCHAR(200) NOT NULL,
    password_salt       VARCHAR(200) NOT NULL,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_companies (
    user_id             INTEGER NOT NULL REFERENCES users(user_id),
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    role                VARCHAR(20) NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, company_id)
);

CREATE TABLE IF NOT EXISTS accounts (
    account_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    code                VARCHAR(10) NOT NULL,
    name                VARCHAR(100) NOT NULL,
    account_type        VARCHAR(20) NOT NULL,
    balance_side        VARCHAR(10) NOT NULL DEFAULT 'debit',
    is_control_account  BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(company_id, code),
    CHECK (account_type IN ('asset','liability','equity','revenue','expense')),
    CHECK (balance_side IN ('debit','credit'))
);

CREATE TABLE IF NOT EXISTS sub_accounts (
    sub_account_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    account_id          INTEGER NOT NULL REFERENCES accounts(account_id),
    code                VARCHAR(20) NOT NULL,
    name                VARCHAR(200) NOT NULL,
    external_code       VARCHAR(50),
    balance             NUMERIC(15,2) DEFAULT 0,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(company_id, account_id, code)
);

CREATE TABLE IF NOT EXISTS account_sets (
    account_set_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    source_company_id   INTEGER REFERENCES companies(company_id),
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS account_set_accounts (
    account_set_account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_set_id      INTEGER NOT NULL REFERENCES account_sets(account_set_id) ON DELETE CASCADE,
    code                VARCHAR(10) NOT NULL,
    name                VARCHAR(100) NOT NULL,
    account_type        VARCHAR(20) NOT NULL,
    balance_side        VARCHAR(10) NOT NULL DEFAULT 'debit',
    is_control_account  BOOLEAN DEFAULT FALSE,
    default_tax_code    VARCHAR(20),
    display_order       INTEGER DEFAULT 0,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_set_id, code),
    CHECK (account_type IN ('asset','liability','equity','revenue','expense')),
    CHECK (balance_side IN ('debit','credit'))
);

CREATE TABLE IF NOT EXISTS account_set_sub_accounts (
    account_set_sub_account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_set_account_id INTEGER NOT NULL REFERENCES account_set_accounts(account_set_account_id) ON DELETE CASCADE,
    code                VARCHAR(20) NOT NULL,
    name                VARCHAR(200) NOT NULL,
    external_code       VARCHAR(50),
    opening_balance     NUMERIC(15,2) DEFAULT 0,
    is_active           BOOLEAN DEFAULT TRUE,
    display_order       INTEGER DEFAULT 0,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_set_account_id, code)
);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS account_set_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'companies'
          AND constraint_name = 'companies_account_set_id_fkey'
    ) THEN
        ALTER TABLE companies
        ADD CONSTRAINT companies_account_set_id_fkey
        FOREIGN KEY (account_set_id) REFERENCES account_sets(account_set_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS tax_codes (
    tax_code_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    code                VARCHAR(20) NOT NULL,
    name                VARCHAR(100) NOT NULL,
    tax_kind            VARCHAR(20) NOT NULL,
    tax_rate            NUMERIC(5,2) NOT NULL,
    is_purchase_credit  BOOLEAN DEFAULT FALSE,
    is_taxable          BOOLEAN DEFAULT TRUE,
    requires_invoice    BOOLEAN DEFAULT FALSE,
    default_purchase_credit_rate NUMERIC(5,2) DEFAULT 0,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(company_id, code),
    CHECK (tax_kind IN ('sales','purchase','non_taxable','exempt','out_of_scope'))
);

CREATE TABLE IF NOT EXISTS business_partners (
    partner_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    code                VARCHAR(30) NOT NULL,
    name                VARCHAR(200) NOT NULL,
    partner_type        VARCHAR(20) NOT NULL DEFAULT 'supplier',
    invoice_status      VARCHAR(20) NOT NULL DEFAULT 'unknown',
    registration_number VARCHAR(20),
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(company_id, code),
    CHECK (partner_type IN ('customer','supplier','both','other')),
    CHECK (invoice_status IN ('qualified','exempt','unregistered','unknown'))
);

CREATE TABLE IF NOT EXISTS journal_vouchers (
    voucher_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    entry_date          DATE NOT NULL,
    entry_number        VARCHAR(20) NOT NULL,
    reference           VARCHAR(100),
    created_by          INTEGER REFERENCES users(user_id),
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(company_id, entry_number)
);

CREATE TABLE IF NOT EXISTS journal_lines (
    line_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id          BIGINT NOT NULL REFERENCES journal_vouchers(voucher_id) ON DELETE CASCADE,
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    line_no             INTEGER NOT NULL,
    side                VARCHAR(6) NOT NULL,
    account_id          INTEGER NOT NULL REFERENCES accounts(account_id),
    sub_account_id      INTEGER DEFAULT 0,
    amount              NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    tax_code_id         INTEGER REFERENCES tax_codes(tax_code_id),
    tax_rate            NUMERIC(5,2),
    tax_amount          NUMERIC(15,2) DEFAULT 0,
    tax_input_type      VARCHAR(10) DEFAULT 'excluded',
    description         TEXT,
    partner_id          INTEGER REFERENCES business_partners(partner_id),
    invoice_number      VARCHAR(100),
    invoice_registration_number VARCHAR(20),
    invoice_status      VARCHAR(20),
    purchase_credit_rate NUMERIC(5,2),
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(voucher_id, line_no),
    CHECK (side IN ('debit','credit'))
);

ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS partner_id INTEGER REFERENCES business_partners(partner_id);
ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(100);
ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS invoice_registration_number VARCHAR(20);
ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS invoice_status VARCHAR(20);
ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS purchase_credit_rate NUMERIC(5,2);
ALTER TABLE journal_lines ALTER COLUMN sub_account_id SET DEFAULT 0;

DO $$
DECLARE
    fk_name TEXT;
BEGIN
    SELECT tc.constraint_name
      INTO fk_name
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name
       AND tc.table_schema = kcu.table_schema
     WHERE tc.constraint_type = 'FOREIGN KEY'
       AND tc.table_name = 'journal_lines'
       AND kcu.column_name = 'sub_account_id'
     LIMIT 1;

    IF fk_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE journal_lines DROP CONSTRAINT %I', fk_name);
    END IF;
END $$;

UPDATE journal_lines
SET sub_account_id = 0
WHERE sub_account_id IS NULL;

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS default_tax_code_id INTEGER REFERENCES tax_codes(tax_code_id);
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS balance_side VARCHAR(10);
UPDATE accounts
SET balance_side = CASE
    WHEN account_type IN ('asset', 'expense') THEN 'debit'
    ELSE 'credit'
END
WHERE balance_side IS NULL;
ALTER TABLE accounts ALTER COLUMN balance_side SET DEFAULT 'debit';
ALTER TABLE accounts ALTER COLUMN balance_side SET NOT NULL;
ALTER TABLE tax_codes ADD COLUMN IF NOT EXISTS is_taxable BOOLEAN DEFAULT TRUE;
ALTER TABLE tax_codes ADD COLUMN IF NOT EXISTS requires_invoice BOOLEAN DEFAULT FALSE;
ALTER TABLE tax_codes ADD COLUMN IF NOT EXISTS default_purchase_credit_rate NUMERIC(5,2) DEFAULT 0;
ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS creditable_tax_amount NUMERIC(15,2) DEFAULT 0;
ALTER TABLE journal_lines ADD COLUMN IF NOT EXISTS non_creditable_tax_amount NUMERIC(15,2) DEFAULT 0;
DROP INDEX IF EXISTS idx_journal_lines_legacy_source;
ALTER TABLE journal_lines DROP COLUMN IF EXISTS source_entry_id;
ALTER TABLE journal_lines DROP COLUMN IF EXISTS source_side;
DROP TABLE IF EXISTS journal_entries;

UPDATE tax_codes
SET is_taxable = CASE WHEN tax_rate > 0 THEN TRUE ELSE FALSE END
WHERE is_taxable IS NULL;

UPDATE tax_codes
SET requires_invoice = CASE WHEN tax_kind = 'purchase' AND is_purchase_credit = TRUE THEN TRUE ELSE FALSE END
WHERE requires_invoice IS NULL;

UPDATE tax_codes
SET default_purchase_credit_rate = CASE WHEN is_purchase_credit = TRUE THEN 100 ELSE 0 END
WHERE default_purchase_credit_rate IS NULL;

CREATE TABLE IF NOT EXISTS sub_account_balances (
    balance_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(company_id),
    sub_account_id      INTEGER NOT NULL REFERENCES sub_accounts(sub_account_id),
    fiscal_year         INTEGER NOT NULL,
    month               INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    balance             NUMERIC(15,2) NOT NULL,
    UNIQUE(company_id, sub_account_id, fiscal_year, month)
);

CREATE TABLE IF NOT EXISTS annual_carry_forwards (
    carry_forward_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL REFERENCES companies(company_id),
    source_fiscal_year_start DATE NOT NULL,
    source_fiscal_year_end   DATE NOT NULL,
    next_fiscal_year_start   DATE NOT NULL,
    entry_number             VARCHAR(30) NOT NULL,
    equity_account_id        INTEGER NOT NULL REFERENCES accounts(account_id),
    net_income               NUMERIC(15,2) NOT NULL,
    created_by               INTEGER REFERENCES users(user_id),
    created_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(company_id, next_fiscal_year_start),
    UNIQUE(company_id, entry_number)
);

CREATE INDEX IF NOT EXISTS idx_user_companies_company ON user_companies(company_id);
CREATE INDEX IF NOT EXISTS idx_accounts_company ON accounts(company_id);
CREATE INDEX IF NOT EXISTS idx_sub_accounts_company_account ON sub_accounts(company_id, account_id);
CREATE INDEX IF NOT EXISTS idx_account_sets_source_company ON account_sets(source_company_id);
CREATE INDEX IF NOT EXISTS idx_account_set_accounts_set ON account_set_accounts(account_set_id, display_order, code);
CREATE INDEX IF NOT EXISTS idx_account_set_sub_accounts_parent ON account_set_sub_accounts(account_set_account_id, display_order, code);
CREATE INDEX IF NOT EXISTS idx_tax_codes_company ON tax_codes(company_id);
CREATE INDEX IF NOT EXISTS idx_business_partners_company ON business_partners(company_id);
CREATE INDEX IF NOT EXISTS idx_journal_vouchers_company_date ON journal_vouchers(company_id, entry_date);
CREATE INDEX IF NOT EXISTS idx_journal_vouchers_company_number ON journal_vouchers(company_id, entry_number);
CREATE INDEX IF NOT EXISTS idx_journal_lines_voucher ON journal_lines(voucher_id, line_no);
CREATE INDEX IF NOT EXISTS idx_journal_lines_company_account ON journal_lines(company_id, account_id, sub_account_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_company_partner ON journal_lines(company_id, partner_id);
CREATE INDEX IF NOT EXISTS idx_sub_account_balances_company_period ON sub_account_balances(company_id, fiscal_year, month);
CREATE INDEX IF NOT EXISTS idx_annual_carry_forwards_company_start ON annual_carry_forwards(company_id, next_fiscal_year_start);
